# database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=idid@123

# Secret Manager not used locally; avoids creating SecretManagerServiceClient on startup
#spring.cloud.gcp.secretmanager.enabled=false

server.port=8080
