# database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/shopify
spring.datasource.username=developer
spring.datasource.password=P@ssw0rd

# Secret Manager not used locally; avoids creating SecretManagerServiceClient on startup
#spring.cloud.gcp.secretmanager.enabled=false

server.port=8080
