-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.book_information
(
    id bigint NOT NULL,
    authors_name character varying(255) COLLATE pg_catalog."default",
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    publication_year integer,
    publisher character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT book_information_pkey PRIMARY KEY (id),
    CONSTRAINT ukkmm57q5icmcbhniby4mcn0sgm UNIQUE (category)
    );

CREATE TABLE IF NOT EXISTS public.book_information_copies
(
    book_information_id bigint NOT NULL,
    book_id bigint NOT NULL,
    CONSTRAINT book_information_copies_pkey PRIMARY KEY (book_id)
    );

CREATE TABLE IF NOT EXISTS public.books
(
    id bigint NOT NULL,
    isbn character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT books_pkey PRIMARY KEY (id),
    CONSTRAINT ukkibbepcitr0a3cpk3rfr7nihn UNIQUE (isbn)
    );

CREATE TABLE IF NOT EXISTS public.borrowed_books
(
    id bigint NOT NULL,
    borrowed_date date NOT NULL,
    due_date date NOT NULL,
    returned_date date,
    book_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT borrowed_books_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.librarians
(
    id bigint NOT NULL,
    date_joined date,
    date_of_birth date,
    email character varying(100) COLLATE pg_catalog."default",
    employee_number character varying(30) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(30) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT librarians_pkey PRIMARY KEY (id),
    CONSTRAINT uk_librarian_employee_number UNIQUE (employee_number),
    CONSTRAINT ukd9i7br4tob7m4sijpjbfxpfs1 UNIQUE (phone_number),
    CONSTRAINT ukmhsi31073cpev37mt53w0tnsl UNIQUE (email),
    CONSTRAINT ukqwm8rcxaed0c2rtti4cmqkc4y UNIQUE (user_id)
    );

CREATE TABLE IF NOT EXISTS public.students
(
    id bigint NOT NULL,
    admission_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    gender character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nationality character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(13) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT students_pkey PRIMARY KEY (id),
    CONSTRAINT uk4ijilwehsq4n3vhrdlq722lnc UNIQUE (admission_number),
    CONSTRAINT uk_student_email UNIQUE (email),
    CONSTRAINT uk_student_phone_number UNIQUE (phone_number),
    CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id)
    );

CREATE TABLE IF NOT EXISTS public.system_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    permission_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT system_permissions_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.system_roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    role_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT system_roles_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.system_roles_system_permissions
(
    role_id bigint NOT NULL,
    permissions_id bigint NOT NULL,
    CONSTRAINT system_roles_system_permissions_pkey PRIMARY KEY (role_id, permissions_id)
    );

CREATE TABLE IF NOT EXISTS public.system_users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    is_active boolean,
    last_logged_in_at timestamp(6) without time zone,
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role_id bigint,
    CONSTRAINT system_users_pkey PRIMARY KEY (id),
    CONSTRAINT uktr0kj1o2dqfwm13a6fvwrg867 UNIQUE (username)
    );

ALTER TABLE IF EXISTS public.book_information_copies
    ADD CONSTRAINT fkafsj5x4xbvpbaf6o1qthbwbtf FOREIGN KEY (book_information_id)
    REFERENCES public.book_information (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.book_information_copies
    ADD CONSTRAINT fkf35ojmq7jpjkmie2pxhh94pqw FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS book_information_copies_pkey
    ON public.book_information_copies(book_id);


ALTER TABLE IF EXISTS public.borrowed_books
    ADD CONSTRAINT fk9cr693ow3wqksocky0m2cwrnk FOREIGN KEY (user_id)
    REFERENCES public.system_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.borrowed_books
    ADD CONSTRAINT fkirp80rty69v7va8179fdkbrls FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.librarians
    ADD CONSTRAINT fk53nvpe670as86ivun3ho9lq1r FOREIGN KEY (user_id)
    REFERENCES public.system_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukqwm8rcxaed0c2rtti4cmqkc4y
    ON public.librarians(user_id);


ALTER TABLE IF EXISTS public.students
    ADD CONSTRAINT fkafybp4e02pw57b8kbngk4umk3 FOREIGN KEY (user_id)
    REFERENCES public.system_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukg4fwvutq09fjdlb4bb0byp7t
    ON public.students(user_id);


ALTER TABLE IF EXISTS public.system_roles_system_permissions
    ADD CONSTRAINT fk8txh257vyff2if2gisf4hyjkg FOREIGN KEY (role_id)
    REFERENCES public.system_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.system_roles_system_permissions
    ADD CONSTRAINT fkpgj7xpkksytfl2aia56ubatau FOREIGN KEY (permissions_id)
    REFERENCES public.system_permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.system_users
    ADD CONSTRAINT fkuh6yk6r9lnqn6am45w2df5gv FOREIGN KEY (role_id)
    REFERENCES public.system_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;